AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        created:
            type: datetime
            nullable: false
        logged:
            type: datetime
            nullable: true
        roles:
            type: string
            nullable: false
            length: 25
            fixed: false
        gravatar:
            type: string
            nullable: false
            length: 255
            fixed: false
        active:
            type: boolean
            nullable: false
        homepage:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
